/* ============================ TRIP DATA ============================ */
/* Shared by itinerary.html and checklist.html — edit here once. */
const TRIP = {
  kr: {
    accent:'#c06a3a', soft:'#33200f',
    days:[
      { id:'kr1', date:'2026-07-10', dow:'Fri', title:'Arrival + Work Day', area:'Jongno, Seoul',
        stops:[
          {n:'Incheon Airport',lat:37.4602,lng:126.4407},
          {n:'Eight Rest Hostel, Jongno',lat:37.5710,lng:126.9910},
          {n:'Insadong-gil',lat:37.5740,lng:126.9850},
          {n:'Gwangjang Market',lat:37.5701,lng:126.9996},
        ],
        blocks:[
          {t:'7:00 AM', x:'<b>Incheon Airport</b> — AREX to Seoul (~50 min). Pick up T-money + pocket WiFi.', major:true},
          {t:'8:30 AM', x:'Drop luggage at <b>Eight Rest Hostel</b>, Jongno (233-1).'},
          {t:'10 AM–7 PM', x:'<b>Work from a café</b> — Namusairo Coffee.<span class="sub"> Opens 7:30 AM, closes 8:30 PM; quiet, fast WiFi.</span>', major:true},
          {t:'1–3 PM', x:'<b>Mandu lunch</b> — Gaeseong Traditional Dumpling House (Insadong) or Bukchon Son-mandu.', chips:[{k:'warn',l:'Gaeseong closes 3 PM, reopens 4'},{k:'note',l:'Bukchon till 7:30 PM'}]},
          {t:'7:15 PM', x:'<b>Dinner</b> around Jongno.'},
          {t:'8:00 PM', x:'<b>Insadong-gil + Ssamzigil</b>, then Gwangjang Market.', chips:[{k:'warn',l:'Ssamzigil closes 8:30 PM'},{k:'note',l:'Gwangjang till 10:30 PM'}]},
          {t:'9:00 PM', x:'<b>Jongno 3-ga Pocha Street</b> — pojangmacha, 5 min from the hostel.', major:true},
        ]},
      { id:'kr2', date:'2026-07-11', dow:'Sat', title:'Seoul — the big loop', area:'Jongno → Seongsu → Gangnam → Namsan → Hongdae',
        stops:[
          {n:'Cheonggyecheon',lat:37.5696,lng:126.9784},
          {n:'Gyeongbokgung',lat:37.5796,lng:126.9770},
          {n:'Musinsa Seongsu',lat:37.5443,lng:127.0557},
          {n:'T1 Café & Arena, Gangnam',lat:37.5045,lng:127.0490},
          {n:'Starfield Library, COEX',lat:37.5128,lng:127.0590},
          {n:'N Seoul Tower',lat:37.5512,lng:126.9882},
          {n:'T1 Base Camp, Hongdae',lat:37.5563,lng:126.9236},
        ],
        blocks:[
          {t:'7:30 AM', x:'<b>Run</b> along Cheonggyecheon stream (1 hr) — flat, lit, 24/7.', major:true},
          {t:'9:00 AM', x:'Check out of Eight Rest; move luggage to <b>Brown Suites</b>.'},
          {t:'10:30 AM', x:'<b>Cheongsudang Bakery</b>, Iksundong.', chips:[{k:'note',l:'10:30 AM – 8 PM'}]},
          {t:'11:00 AM', x:'<b>Insadong Culture Street</b>.'},
          {t:'12:30 PM', x:'<b>Gyeongbokgung Palace</b>.', major:true, chips:[{k:'warn',l:'closes 5 PM · shut Tue'}]},
          {t:'2:00 PM', x:'<b>Kim Gyeongja Wonjo Sonkal Guksu</b>, Seongdong — kalguksu + bossam.', chips:[{k:'warn',l:'closes 9 PM · CLOSED SUN'}]},
          {t:'2:45 PM', x:'<b>Musinsa Megastore Seongsu</b> — shopping.', chips:[{k:'note',l:'till 10 PM'}]},
          {t:'3:30 PM', x:'<b>T1 Café &amp; Arena</b>, Gangnam.', major:true, chips:[{k:'warn',l:'closes 8 PM · CLOSED SUN'}]},
          {t:'4:30 PM', x:'<b>Starfield Library</b>, COEX Mall.', chips:[{k:'note',l:'till 10 PM'}]},
          {t:'5:30 PM', x:'<b>Samwon Garden</b> KBBQ, Gangnam.', chips:[{k:'reserve',l:'book ahead · 9 PM Sat'}]},
          {t:'7:30 PM', x:'<b>N Seoul Tower / Namsan</b> — bibimbap at the cable-car base.', major:true, chips:[{k:'note',l:'11 PM Sat'}]},
          {t:'9:00 PM', x:'<b>Myeongdong</b> — skincare browse. <span class="sub">Don\'t eat here.</span>'},
          {t:'10:00 PM', x:'<b>T1 Base Camp</b>, Hongdae — PC bang + merch, tax refund inside.', major:true, chips:[{k:'note',l:'24/7'}]},
        ]},
      { id:'kr3', date:'2026-07-12', dow:'Sun', title:'Seoul → Daejeon (MSI day)', area:'Inwangsan → Gangnam → Daejeon',
        stops:[
          {n:'Inwangsan trailhead',lat:37.5816,lng:126.9590},
          {n:'Pro Soy Crab, Gangnam',lat:37.5046,lng:127.0490},
          {n:'Seoul Station',lat:37.5547,lng:126.9707},
          {n:'Expo Science Park, Daejeon',lat:36.3745,lng:127.3886},
          {n:'Daejeon Station',lat:36.3315,lng:127.4347},
        ],
        blocks:[
          {t:'6:00 AM', x:'<b>Scenic 7-Eleven</b> (Inwangsan-ro, Sajik) — Namsan view, trail snacks.', chips:[{k:'note',l:'24/7'}]},
          {t:'6:30 AM', x:'<b>Inwangsan hike</b> — starts right behind the 7-Eleven.', major:true},
          {t:'9:30 AM', x:'<b>Brown Suites</b> — shower, check out.'},
          {t:'10:30 AM', x:'<b>Pro Soy Crab</b>, Gangnam — raw marinated crab.', chips:[{k:'note',l:'till 11 PM'}]},
          {t:'12:30 PM', x:'<b>Seoul Station → KTX to Daejeon</b> (~50 min).', major:true, chips:[{k:'reserve',l:'book korail.com'}]},
          {t:'1:45 PM', x:'<b>Daejeon Yuseong Nakwon Onsen Hotel</b> — check in, drop bags.'},
          {t:'3:00 PM', x:'<b>Fan Festa</b> — Hanbit Plaza, Expo Science Park (Yuseong).', major:true, chips:[{k:'note',l:'runs 3–8 PM · stay 1.5–2 hr'}]},
          {t:'6:00 PM', x:'<b>MSI Finals.</b>', major:true, chips:[{k:'reserve',l:'confirm venue + start from ticket'}]},
          {t:'Late', x:'After-party / Daejeon nightlife.'},
        ]},
      { id:'kr4', date:'2026-07-13', dow:'Mon', title:'Daejeon → Incheon (Departure)', area:'Daejeon → Seoul → Incheon',
        stops:[
          {n:'Daejeon Station',lat:36.3315,lng:127.4347},
          {n:'Seoul Station',lat:37.5547,lng:126.9707},
          {n:'Incheon Airport',lat:37.4602,lng:126.4407},
        ],
        blocks:[
          {t:'7:00 AM', x:'Check out of the Daejeon hotel.'},
          {t:'7:30 AM', x:'<b>Daejeon Station → KTX to Seoul</b> (~50 min).', major:true},
          {t:'9:15 AM', x:'<b>Seoul Station → AREX Express to Incheon T1</b> (~43 min).', major:true},
          {t:'10:45 AM', x:'<b>Incheon Airport</b> — check in &amp; clear security.', chips:[{k:'warn',l:'be here by 10:45 AM'}]},
          {t:'12:55 PM', x:'<b>Departure to Japan.</b>', major:true},
        ]},
    ]
  },
  jp: {
    accent:'#4d82a6', soft:'#15293a',
    days:[
      { id:'jp1', date:'2026-07-13', dow:'Mon', title:'Arrive + settle', area:'Narita → Shibuya → Miyamaedaira',
        stops:[
          {n:'Narita Airport',lat:35.7720,lng:140.3929},
          {n:'Shibuya',lat:35.6595,lng:139.7005},
          {n:'Miyamaedaira (home base)',lat:35.5876,lng:139.5710},
        ],
        blocks:[
          {t:'3:30 PM', x:'<b>Land Narita.</b> Immigration + baggage + customs ~45–60 min.', major:true},
          {t:'At airport', x:'Pocket WiFi; set up Suica/Pasmo (or Welcome Suica).'},
          {t:'~5:00 PM', x:'<b>N\'EX Narita → Shibuya</b> (~75 min).', major:true, chips:[{k:'note',l:'round-trip ¥5,000 — buy on arrival'}]},
          {t:'~6:15 PM', x:'Shibuya → <b>Tokyu Den-en-toshi Line → Miyamaedaira</b> (24 min).'},
          {t:'~6:50 PM', x:'<b>Home.</b> Drop bags, freshen up.'},
          {t:'Evening', x:'Dinner in Jiyugaoka (La Vita) or near home. Early night.'},
        ]},
      { id:'jp2', date:'2026-07-14', dow:'Tue', title:'Shinjuku + Kabukicho', area:'Shinjuku (west side)',
        stops:[
          {n:'JINS Shinjuku flagship',lat:35.6915,lng:139.7036},
          {n:'Tokyo Metropolitan Gov Bldg',lat:35.6896,lng:139.6917},
          {n:'Kabukicho',lat:35.6949,lng:139.7028},
          {n:'Omoide Yokocho',lat:35.6932,lng:139.6995},
        ],
        blocks:[
          {t:'Morning', x:'Café in Shinjuku.'},
          {t:'10:30 AM', x:'<b>JINS Shinjuku flagship</b> — eye test, glasses in ~30 min.', major:true, chips:[{k:'note',l:'passport · tax-free'}]},
          {t:'Late AM', x:'<b>Kitamura Camera</b> flagship — 7 floors.', chips:[{k:'note',l:'passport · tax-free'}]},
          {t:'Midday', x:'<b>Tokyo Met Gov observation deck</b> (free) + Uniqlo/GU flagship.'},
          {t:'Sunset', x:'Met Bldg deck at sunset if missed earlier.'},
          {t:'Dinner', x:'<b>Kabukicho</b> — Tokiwatei (0-sec lemon sour + yakiniku) or Jingisukan lamb BBQ.', major:true, chips:[{k:'reserve',l:'reserve Tokiwatei ahead'}]},
          {t:'Evening', x:'<b>Omoide Yokocho</b> yakitori alley.', chips:[{k:'note',l:'~4 PM–midnight · some cash only'}]},
          {t:'After 12', x:'<b>Torikizoku Kabukicho</b> (to 4 AM) or Gekibutori (24h).', chips:[{k:'note',l:'cash for some'}]},
          {t:'To 4 AM', x:'<b>Shinjuku Batting Center</b> — ¥300/25 pitches.', major:true, chips:[{k:'warn',l:'cash only'}]},
        ]},
      { id:'jp3', date:'2026-07-15', dow:'Wed', title:'Museums + old town', area:'Ueno → Kappabashi → Asakusa → Yanaka',
        stops:[
          {n:'Tokyo National Museum, Ueno',lat:35.7188,lng:139.7766},
          {n:'Kappabashi Kitchen St',lat:35.7140,lng:139.7900},
          {n:'Senso-ji, Asakusa',lat:35.7148,lng:139.7967},
          {n:'Yanaka Ginza',lat:35.7276,lng:139.7660},
        ],
        blocks:[
          {t:'Morning', x:'Café in Ueno.'},
          {t:'9:30 AM', x:'<b>Tokyo National Museum</b> — buy online to skip the queue.', major:true, chips:[{k:'warn',l:'¥1,000 · CLOSED Mon'}]},
          {t:'Midday', x:'Ueno Park walk → <b>Kappabashi Kitchen Street</b> (~10 min).'},
          {t:'Afternoon', x:'<b>Senso-ji / Asakusa</b> browse.'},
          {t:'Late PM', x:'<b>Yanaka Ginza</b> + Shinimonogurui hanko stamp shop.', major:true, chips:[{k:'warn',l:'hanko open Wed only (shut Thu/Fri)'}]},
          {t:'Sunset', x:'Yuyake Dandan sunset stairs, street snacks. Home via Shibuya.'},
        ]},
      { id:'jp4', date:'2026-07-16', dow:'Thu', title:'Free & easy (split day)', area:'Kasai / Akihabara  •  Kichijoji / Daikanyama',
        stops:[
          {n:'E-Chan ramen, Fudo-mae',lat:35.6243,lng:139.7156},
          {n:'Tokyo Sea Life Park, Kasai',lat:35.6406,lng:139.8632},
          {n:'Akihabara RAILYARD',lat:35.6984,lng:139.7731},
          {n:'Kichijoji / Inokashira',lat:35.7022,lng:139.5803},
          {n:'Daikanyama T-Site',lat:35.6485,lng:139.7030},
          {n:'Kagurazaka',lat:35.7016,lng:139.7405},
        ],
        blocks:[
          {t:'6:30 AM', x:'<b>Asa ramen</b> — E-Chan Shokudo, Fudo-mae. Queue early, done ~8 AM.', major:true, chips:[{k:'warn',l:'6:30–11 AM · CLOSED Wed'}]},
          {t:'A-track', x:'<b>Tokyo Sea Life Park</b> aquarium, Kasai.', chips:[{k:'warn',l:'¥700 · last entry 4 PM · shut Wed'}]},
          {t:'A-track', x:'<b>Akihabara RAILYARD</b> — train-themed goods.', chips:[{k:'note',l:'passport · tax-free'}]},
          {t:'B-track', x:'<b>Kichijoji</b> — Inokashira Park, Harmonica Yokocho.'},
          {t:'B-track', x:'<b>Daikanyama T-Site</b> → Nakameguro canal walk.'},
          {t:'B-eve', x:'<b>Kagurazaka</b> — geisha alleys, French bakeries (best after dark).', major:true},
        ]},
      { id:'jp5', date:'2026-07-17', dow:'Fri', title:'Kamakura + coast', area:'Kamakura → Hase → Enoshima',
        stops:[
          {n:'Hokokuji Bamboo Grove',lat:35.3206,lng:139.5640},
          {n:'Tsurugaoka Hachimangu',lat:35.3258,lng:139.5563},
          {n:'Kotoku-in Great Buddha',lat:35.3169,lng:139.5358},
          {n:'Hase-dera',lat:35.3124,lng:139.5320},
          {n:'Enoshima',lat:35.2996,lng:139.4805},
        ],
        blocks:[
          {t:'Optional', x:'6:30 AM E-Chan asa ramen (open Fri) before heading out.'},
          {t:'9–9:30 AM', x:'Miyamaedaira → Shibuya → <b>JR Shonan-Shinjuku → Kamakura</b> (~70 min).', major:true},
          {t:'Morning', x:'<b>Hokokuji Bamboo Grove</b> — matcha cafe inside.', chips:[{k:'note',l:'9 AM · ¥500'}]},
          {t:'Central', x:'<b>Tsurugaoka Hachimangu</b> (main shrine) + Komachi-dori lunch.', major:true},
          {t:'West', x:'<b>Kotoku-in Great Buddha</b> + Hase-dera (sea views).'},
          {t:'Coast', x:'Ride the <b>Enoden</b> west — Inamuragasaki sunset point, Shichirigahama, Slam Dunk crossing.'},
          {t:'~6:50 PM', x:'<b>Enoshima</b> — Sea Candle for sunset + Enoshima Shrine. Dinner on the island.', major:true, chips:[{k:'warn',l:'EITHER coast OR hill shrines — not both'}]},
        ]},
      { id:'jp6', date:'2026-07-18', dow:'Sat', title:'Last day + Narita night', area:'Shibuya → Ginza → Togoshi → Narita',
        stops:[
          {n:'Gallery 2, Shibuya',lat:35.6618,lng:139.6995},
          {n:'Itoya, Ginza',lat:35.6717,lng:139.7650},
          {n:'Togoshi Ginza',lat:35.6113,lng:139.7156},
          {n:'Miyamaedaira (bags)',lat:35.5876,lng:139.5710},
          {n:'Narita Airport',lat:35.7720,lng:140.3929},
        ],
        blocks:[
          {t:'Morning', x:'<b>Gallery 2</b> volleyball store, Shibuya.', chips:[{k:'note',l:'11 AM–8 PM · passport'}]},
          {t:'Midday', x:'<b>Itoya Ginza</b> stationery — 12 floors.', chips:[{k:'note',l:'10 AM–8 PM Sat · passport'}]},
          {t:'Afternoon', x:'<b>Togoshi Ginza</b> — longest shopping street, street food.', chips:[{k:'note',l:'skip first if running late'}]},
          {t:'6:00–6:30 PM', x:'Back to <b>Miyamaedaira</b>, collect bags.', major:true},
          {t:'7:00 PM', x:'Miyamaedaira → Shibuya with luggage (be there by 7:15 PM).', chips:[{k:'warn',l:'tight window'}]},
          {t:'7:45 PM', x:'<b>LAST N\'EX Shibuya → Narita</b> (~75 min, arrives ~9:12 PM).', major:true, chips:[{k:'reserve',l:'reserved seats required'}]},
          {t:'~9:30 PM', x:'Airport → <b>Hotel MyStays Premier Narita</b> — free shuttle (~15 min).', chips:[{k:'note',l:'confirm last run · taxi ¥2–3k backup'}]},
        ]},
      { id:'jp7', date:'2026-07-19', dow:'Sun', title:'Departure', area:'Narita',
        stops:[ {n:'Narita Airport',lat:35.7720,lng:140.3929} ],
        blocks:[
          {t:'~4:30 AM', x:'Wake.'},
          {t:'~5:30 AM', x:'<b>Hotel shuttle to airport</b> (first ~5:00–5:30 AM, no booking).', major:true, chips:[{k:'note',l:'confirm timetable at check-in'}]},
          {t:'~6:00 AM', x:'At Narita. Bag drop closes ~7:20 AM; be checked in by ~6:30 AM.', chips:[{k:'warn',l:'don\'t cut it close'}]},
          {t:'8:20 AM', x:'<b>Departure.</b>', major:true},
        ]},
    ]
  }
};
